# TODO: Revise when an AskUserQuestion like tool comes to Gemini
description = "Interview to flesh out a plan/spec"
prompt = """
I roughly outlined what I plan to do in the SPEC.md file.

Interview me in detail by asking questions. Ask about technical implementation, UI & UX, edge cases,
concerns, tradeoffs. Don't ask obvious questions, dig into the hard parts I might not have considered.

Keep interviewing until we've covered everything, then write a complete spec to SPEC.md.
"""
